In [132]:
import pandas as pd
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.graph_objs import Scatter, Figure, Layout
init_notebook_mode(connected=True)
%matplotlib inline

In [133]:
a = pd.read_json("test.json").to_json()
pd.read_json(a)

,_id,amount,description,medium,payee_id,status,transaction_date,type
0,5a57b09d6514d52c7774a3b1,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-15,deposit
1,5a57b09d6514d52c7774a3b2,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-30,deposit
2,5a57b09d6514d52c7774a3b3,200,work,balance,5a563d355eaa612c093b0b8b,executed,2018-1-15,deposit
3,5a57b0ab6514d52c7774a3c8,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-15,deposit
4,5a57b0ab6514d52c7774a3c9,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-30,deposit
5,5a57b0ab6514d52c7774a3ca,200,work,balance,5a563d355eaa612c093b0b8b,executed,2018-1-15,deposit

In [134]:
deposits = pd.read_json("deposits.json")
purchases = pd.read_json("purchases.json")
data = pd.read_csv("legit_data.csv")

# Segmentation

In [153]:
data["Posted Date"] = pd.to_datetime(data["Posted Date"])
cleaned_data = data.iloc[:, [0,1,4]]
segmented_spending = cleaned_data.groupby("Category").resample("M", on="Posted Date").sum()
segmented_spending["Amount"] = segmented_spending["Amount"].fillna(0)
a = segmented_spending.reset_index().groupby("Category").sum() / cleaned_data["Amount"].sum()
b = a.sort_values("Amount", ascending=False)[:3]
b.Amount

Category
Restaurant    0.469261
Grocery       0.266563
Stationary    0.149295
Name: Amount, dtype: float64

In [154]:
data

,Amount,Posted Date,Vendor,Description,Category
0,7.98,2014-03-10,ROSS STORES #1034,GENERAL PURCHASE,Clothes
1,139.99,2013-10-25,BEST BUY 00025031,MY BEST BUY ELITE EACH|1.2CUFT STAINLESS ST EACH,Electronics
2,23.98,2013-09-02,BEST BUY 00025031,REWARD ZONE CARD EACH|HP 564 XL INK - BLK EACH|HP,Electronics
3,27.66,2014-06-19,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
4,19.40,2014-06-16,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
5,8.74,2014-06-16,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
6,19.49,2014-06-13,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
7,28.09,2014-06-11,WAL-MART #0137,GENERAL PURCHASE,Grocery
8,37.44,2014-06-11,WM SUPERCENTER #137,GENERAL PURCHASE,Grocery
9,1178.00,2014-05-30,GroceryMANUFACTURERS AS,GENERAL PURCHASE,Grocery
10,176.87,2014-05-20,WAL-MART #4241,GENERAL PURCHASE,Grocery
11,220.33,2014-05-09,STAPLES 00105288,HP 564XL BLK/564 CMY 4PK C EA|INK AND TONER SA...,Grocery
12,27.44,2014-05-01,WAL-MART #0137,GENERAL PURCHASE,Grocery
13,104.50,2014-04-23,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
14,55.27,2014-04-23,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
15,7.98,2014-04-21,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
16,110.82,2014-04-21,WAL-MART #0137,GENERAL PURCHASE,Grocery
17,13.47,2014-04-21,WM SUPERCENTER #137,GENERAL PURCHASE,Grocery
18,142.68,2014-04-17,WM SUPERCENTER #137,GENERAL PURCHASE,Grocery
19,143.46,2014-04-02,WAL-MART #0137,GENERAL PURCHASE,Grocery
20,28.06,2014-03-28,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
21,51.22,2014-03-27,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
22,128.75,2014-03-26,WM SUPERCENTER #137,GENERAL PURCHASE,Grocery
23,41.23,2014-03-10,WAL-MART #0137,GENERAL PURCHASE,Grocery
24,5.99,2014-03-06,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
25,69.90,2014-02-26,WAL-MART #0137,GENERAL PURCHASE,Grocery
26,63.82,2014-02-20,WAL-MART #4241,GENERAL PURCHASE,Grocery
27,119.00,2014-02-20,WAL-MART #4241,GENERAL PURCHASE,Grocery
28,29.16,2014-01-17,WAL-MART #0137,GENERAL PURCHASE,Grocery
29,21.42,2013-11-18,FOOD PYRAMID #69,GENERAL PURCHASE,Grocery
...,...,...,...,...,...
161,335.35,2014-02-21,QUILL CORPORATION,GENERAL PURCHASE,Stationary
162,138.75,2014-02-19,STAPLES 00105288,REMOVABLE POSTER HANGERS 1 EA|REMOVABLE POSTER...,Stationary
163,209.98,2014-01-29,STAPLES 00105288,DURACELL COPPERTOP AA16 DB EA|HP PHOTOSMART 75...,Stationary
164,81.79,2014-01-20,STAPLES 00105288,INK RECYCLING LIMIT 10/MON EA|DIAL COMPLETE HA...,Stationary
165,19.98,2013-12-19,STAPLES 00105288,INK RECYCLING LIMIT 10/MON EA|HP 933XL CYAN IN...,Stationary
166,29.98,2013-12-04,QUILL CORPORATION,GENERAL PURCHASE,Stationary
167,469.20,2013-11-14,QUILL CORPORATION,GENERAL PURCHASE,Stationary
168,24.98,2013-11-08,STAPLES 00105288,HP 933XL MAGENTA INK EA|RCA DICTATING CASSETTE...,Stationary
169,568.49,2013-11-01,QUILL CORPORATION,GENERAL PURCHASE,Stationary
170,56.64,2013-11-01,QUILL CORPORATION,GENERAL PURCHASE,Stationary
171,13.79,2013-10-18,STAPLES 00105288,STAPLES STD SHEET PROT 100 EA,Stationary
172,49.95,2013-10-10,B&C BUSINESS PRODUCTS,GENERAL PURCHASE,Stationary
173,38.95,2013-10-07,STAPLES 00105288,2IN DURABLE VIEW BINDER OR EA|CHARLESTON TAB D...,Stationary
174,48.58,2013-09-30,STAPLES 00105288,INK RECYCLING LIMIT 10/MON EA|HP 564XL BLACK I...,Stationary
175,30.99,2013-09-18,STAPLES 00105288,HP 933 CMY COLOR INK CVP 3 EA,Stationary
176,445.32,2013-09-16,QUILL CORPORATION,GENERAL PURCHASE,Stationary
177,120.36,2013-08-05,B&C BUSINESS PRODUCTS,GENERAL PURCHASE,Stationary
178,27.16,2013-08-05,STAPLES 00105288,STAPLES 8-TAB INSERT 4PK EA,Stationary
179,20.37,2013-07-29,STAPLES 00105288,STAPLES 8-TAB INSERT 4PK EA,Stationary
180,195.42,2013-07-18,STAPLS3144639635000,BROTHER TN221BK BLACK TONE EA|INSERTABLE DIVIDERS,Stationary
181,86.60,2013-07-15,STAPLES 00105288,INK RECYCLING LIMIT 10/MON EA|HP 933 MAGENTA I...,Stationary
182,476.46,2013-07-11,STAPLS3144606170000,MAY 13 APPLE ACCESSORIES EA|MONO CORRECTION TA...,Stationary
183,181.92,2013-07-09,QUILL CORPORATION,GENERAL PURCHASE,Stationary
184,86.32,2014-06-25,BEST WESTERN CIMARRONHT,ROOM CHARGES,Travel
185,258.96,2014-06-23,BEST WESTERN CIMARRONHT,ROOM CHARGES,Travel
186,258.96,2014-06-23,BEST WESTERN CIMARRONHT,ROOM CHARGES,Travel
187,437.10,2013-07-29,AMERICAN AI 0017253953596,AIR TRAVEL,Travel
188,28.00,2013-07-29,AGENT FEE 0017253953596,AIR TRAVEL,Travel
189,28.00,2013-07-10,AGENT FEE 0167252096439,AIR TRAVEL,Travel
190,759.80,2013-07-10,UNITED 0167252096439,AIR TRAVEL,Travel

In [130]:
data["Posted Date"] = pd.to_datetime(data["Posted Date"])
cleaned_data = data.iloc[:, [0,1,4]]
segmented_spending = cleaned_data.groupby("Category").resample("M", on="Posted Date").sum()
segmented_spending = segmented_spending.fillna(0)
data = [
    Scatter(
        x=monthly_purchases.index, # assign x as the dataframe column 'x'
        y=monthly_purchases.iloc[:,0] * -1
    )
]

layout = Layout(
    title='Cleaning',
    yaxis=dict(title='random distribution'),
    xaxis=dict(title='linspace')
)

### Calculate Balance

In [49]:
balance = deposits["amount"].sum() - purchases["amount"].sum()
balance

-2528

## Cleaning Deposits

In [41]:
deposits

,_id,amount,description,medium,payee_id,status,transaction_date,type
0,5a57b09d6514d52c7774a3b1,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-15,deposit
1,5a57b09d6514d52c7774a3b2,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-30,deposit
2,5a57b09d6514d52c7774a3b3,200,work,balance,5a563d355eaa612c093b0b8b,executed,2018-1-15,deposit
3,5a57b0ab6514d52c7774a3c8,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-15,deposit
4,5a57b0ab6514d52c7774a3c9,200,work,balance,5a563d355eaa612c093b0b8b,executed,2017-12-30,deposit
5,5a57b0ab6514d52c7774a3ca,200,work,balance,5a563d355eaa612c093b0b8b,executed,2018-1-15,deposit

## Cleaning Purchases

### Monthly Spending

In [127]:
monthly_purchases

                  2
0
2017-09-30  -165.58
2017-10-31  -290.45
2017-11-30 -2207.94
2017-12-31 -2778.08
2018-01-31  -294.07

In [76]:
chase = pd.read_csv("chase.csv", header=None)
cleaned_chase = chase.iloc[:,[0,2]]
cleaned_chase.iloc[:,0] = pd.to_datetime(cleaned_chase.iloc[:,0])
monthly_purchases = cleaned_chase.resample("M", on=0).sum()
data = [
    Scatter(
        x=monthly_purchases.index, # assign x as the dataframe column 'x'
        y=monthly_purchases.iloc[:,0] * -1
    )
]

layout = Layout(
    title='Cleaning',
    yaxis=dict(title='random distribution'),
    xaxis=dict(title='linspace')
)

fig = Figure(data=data, layout=layout)
iplot(fig)

/Users/averyyip/anaconda3/envs/ds100/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [32]:
cleaned_purchases = purchases[["amount", "description", "purchase_date"]]
cleaned_purchases["purchase_date"] = pd.to_datetime(cleaned_purchases["purchase_date"])
monthly_purchases = cleaned_purchases.resample("M", on="purchase_date").sum()
data = [
    Scatter(
        x=monthly_purchases.index, # assign x as the dataframe column 'x'
        y=monthly_purchases["amount"]
    )
]

layout = Layout(
    title='Cleaning',
    yaxis=dict(title='random distribution'),
    xaxis=dict(title='linspace')
)

fig = Figure(data=data, layout=layout)
iplot(fig)

/Users/averyyip/anaconda3/envs/ds100/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy